```java
try{
   //可能产生异常的代码
   
} catch(Type1 id1) {
   //处理Type1异常的代码
   
} catch(Type2 id2) {
   //处理Type1异常的代码
   
} catch(Type3 id3) {
   //处理Type1异常的代码
}
```

```java
package exception;

import java.util.Scanner

public class Arraylndex {
   
    public stntic void f() {
       int[] a = new int[10];
       a[10] = 10;
       System.out.println("hello");
}    
    public stntic void g() {
       f();   
}

    public stntic void h() {
       int i=10;
       if ( i<100 ) {
          g();
          }   
}
    public stntic void k() {
       try{
          h();
       } catch (NullPointerException e) {
       System.out.println("k()");
       }
}
    public stntic void main(Sting[] args) { 
        try {
           k();
    }catch ( ArraylndexOutOFBoundsException e） {
         System.out.println("Caught");
    }
    System.out.println("main");
  }
}
```
![异常捕捉机制逻辑图](http://p8eerbuco.bkt.clouddn.com/%E5%BC%82%E5%B8%B8%E6%8D%95%E6%8D%89%E6%9C%BA%E5%88%B6.png)
Format: ![Alt Text](url)
