```
 catch 怎么匹配
 ls-A 的关系
 就是说，抛出子类异常会被父类异常的catch给捉到
```
```java
package exception;
class OpenException extends Exception {
}

class CloseException extends OpenException {

}

    public class Arraylndex {
       public static int open() {
       int[] a = new int[10];
       a[10] = 10;
       return -1
    }
    public static void readFile() throws OpenException,CloseException {
        if ( open() == -1 ) {
            throw new CloseException();
        }
    }
    public static void main(String[] args) {
        try {
            readFile();
        } catch (NullpointerException e) {
            //T0D0 Auto- generated catch block
            e.printStackTrace();
        } catch (OpenException e) {
            // T0D0 Auto-generated catch block
            e.printStackTrace();
            System.out.println("Close");
        } catch (OpenException e) {
            // T0D0 Auto-generated catch block
            e.printStackTrace();
            System.out.println("Open");
        }
    }
}    
    
```
#### 捕捉任何异常
```
catch(Exception e){
 System.err.println("Caugh an exception");
}
```
#### 运行时刻异常
```
像 ArraylndexOutOfBoundsException 这样的异常是不需要声明的
但是如果没有适当的机制来捕捉，就会最终导致程序终止,如：

         } catch (Exception e) {
            //T0D0 Auto-generated catch block
            e.printStackTrace();
            System.out.println("Anthing");
        }


package exception;
class OpenException extends Throwable {
}

class CloseException extends Throwable {

}

    public class Arraylndex {
       public static int open() {
       int[] a = new int[10];
       a[10] = 10;
       return -1
    }
    public static void readFile() throws OpenException,CloseException {
        if ( open() == -1 ) {
            throw new OpenException();
        }
    }
    public static void main(String[] args) {
        try {
            readFile();
        } catch (NullpointerException e) {
            //T0D0 Auto- generated catch block
            e.printStackTrace();
        } catch (OpenException e) {
            //T0D0 Auto-generated catch block
            e.printStackTrace();
            System.out.println("Open");
         } catch (Exception e) {
            //T0D0 Auto-generated catch block
            e.printStackTrace();
            System.out.println("Anthing");
        }
    }
    
    
```
