```
# 拿到异常对象之后
##String getMessage();
##String toString();
##void printStackTrace();
#但是肯定是回不去了，而具体的处理逻辑则取决于你的业务逻辑需要


# 再度抛出
catch(Exception e){
  System.err.println("An exception was thrown");
  throw e;
}
##如果在这个层面上需要处理，但是不能做最终的决定
